### PR TITLE
[#6] Update U.S. Web Design Standards components to v0.8

### PR DESCRIPTION
**Pull request by fureigh**
~~This is a WIP until the compiled .scss files are included. Not yet ready for review, but tips on how to get libsass to compile are welcome. :)~~

This pull request updates the U.S. Web Design Standards assets to the latest version (v0.8), per #6.

### CODE REVIEW

**Comment by fureigh** [comment]
Now ready for review.

**Comment by gboone** [comment]
Does this close #6 then or are both of these ready for merging?

**Comment by gboone** [comment]
This looks great @fureigh thanks! This closes #6!

**Comment by fureigh** [comment]
Thanks, @gboone!

**Pull request merged**
