### PR TITLE
Clarify how to get started

### PR DESCRIPTION
**Pull request by fureigh**
This pull request clarifies how to get started working on this project. It includes:
- Adding [Honcho](https://honcho.readthedocs.org),
- Adding an example .env file and
- Updating the README to include getting-started instructions.

I used Honcho because this project has a Procfile. @gboone, if you prefer a different approach, LMK.

### CODE REVIEW

**Comment by fureigh** [comment]
@anthonygarvan Jinx! :) But seriously, thanks for updating the README with setup instructions.

Toward resolving the merge conflict: yours suggests running `python manage.py deploy`, mine takes a Honcho approach. I’m inclined toward using Honcho or dotenv because with those approaches the environment variables are encapsulated and don’t potentially get reset by (or affect) other projects, hang around when no longer relevant, etc. I’m open to other approaches, though. What do you think?

**Comment by catherinedevlin** [comment]
This looks great!  Thanks, @fureigh !

**Comment by anthonygarvan** [comment]
Looks great! Please overwrite my Readme, Honcho is a more polished approach.

**Comment by fureigh** [comment]
Thanks! Merge conflicts are now resolved. @anthonygarvan, I kept the part you added about requesting access and getting an API token.

@gboone, good to go?

**Comment by gboone** [comment]
Looks good to me! Merging.

**Pull request merged**
